/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120384-gdc8e753f32-20250728"
#endif /* AVUTIL_FFVERSION_H */
